require_relative 'cli/copy'
require_relative 'cli/index'
require_relative 'cli/organize'
require_relative 'cli/orient'
require_relative 'cli/search'
require_relative 'cli/rename'
require_relative 'cli/s3push'
